### PR TITLE
fix missing dependency build issue

### PR DESCRIPTION
**Pull request by demon36**

### CODE REVIEW

**Comment by Depado** [comment]
I'm merging this since I couldn't find any viable option to keep using the `github.com/russross/blackfriday/v2` import without breaking other people's repos, even though it's working on my end. 
I'll add a few things and will create a release shortly after. 
Thanks

**Comment by demon36** [comment]
great, dont forget to take a look at the build fix PR in the smallblog repo

**Comment by Depado** [comment]
Yep, heading to that right now haha

**Comment by Depado** [comment]
Alright. I'm going to revert this. 
I think I finally managed to find out what's going on and why I can't use `gpkg.in` in `smallblog`. 
I'm using spf13/cobra which in turn is using cpuguy83/go-md2man which itself uses the `github.com` version of `blackfriday`.
Turns out, I can't use both versions within the same repository.

**Pull request merged**
